// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/aggregator.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Aggregator struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Creator string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Aggregator) Reset()         { *m = Aggregator{} }
func (m *Aggregator) String() string { return proto.CompactTextString(m) }
func (*Aggregator) ProtoMessage()    {}
func (*Aggregator) Descriptor() ([]byte, []int) {
	return fileDescriptor_99d943f9e99cca17, []int{0}
}
func (m *Aggregator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Aggregator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Aggregator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Aggregator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aggregator.Merge(m, src)
}
func (m *Aggregator) XXX_Size() int {
	return m.Size()
}
func (m *Aggregator) XXX_DiscardUnknown() {
	xxx_messageInfo_Aggregator.DiscardUnknown(m)
}

var xxx_messageInfo_Aggregator proto.InternalMessageInfo

func (m *Aggregator) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Aggregator) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Aggregator) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Aggregator)(nil), "supsidacdisaac.pm.pm.Aggregator")
}

func init() { proto.RegisterFile("pm/aggregator.proto", fileDescriptor_99d943f9e99cca17) }

var fileDescriptor_99d943f9e99cca17 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0x4e, 0xc6, 0x20,
	0x14, 0x85, 0x8b, 0x46, 0x8d, 0x8c, 0xb5, 0x03, 0x71, 0x20, 0xc6, 0xc9, 0xa5, 0x30, 0x18, 0x1f,
	0x40, 0x5f, 0xc0, 0xc4, 0xc1, 0xc1, 0x8d, 0x1f, 0x08, 0x32, 0xe0, 0xbd, 0xe1, 0xd2, 0xa4, 0xbe,
	0x85, 0x8f, 0xe5, 0xd8, 0xd1, 0xd1, 0xb4, 0x2f, 0x62, 0xa0, 0xea, 0x42, 0xf8, 0xee, 0x39, 0x27,
	0xf9, 0xf8, 0x05, 0x26, 0x6d, 0x42, 0xc8, 0x3e, 0x98, 0x02, 0x59, 0x61, 0x86, 0x02, 0xfd, 0x40,
	0x13, 0x52, 0x74, 0xc6, 0xba, 0x48, 0xc6, 0x58, 0x85, 0x49, 0x61, 0xba, 0x1c, 0x02, 0x04, 0x68,
	0x05, 0x5d, 0x7f, 0x7b, 0xf7, 0xfa, 0x99, 0xf3, 0xfb, 0xff, 0x7d, 0x3f, 0xf0, 0x93, 0xf8, 0xe6,
	0xfc, 0x2c, 0xd8, 0x15, 0xbb, 0x39, 0x7f, 0xda, 0xa1, 0x17, 0xfc, 0xcc, 0x38, 0x97, 0x3d, 0x91,
	0x38, 0x6a, 0xf7, 0x3f, 0xac, 0x89, 0xcd, 0xbe, 0x4e, 0xc5, 0xf1, 0x9e, 0xfc, 0xe2, 0xc3, 0xe3,
	0xe7, 0x2a, 0xd9, 0xb2, 0x4a, 0xf6, 0xbd, 0x4a, 0xf6, 0xb1, 0xc9, 0x6e, 0xd9, 0x64, 0xf7, 0xb5,
	0xc9, 0xee, 0xe5, 0x2e, 0xc4, 0xf2, 0x3a, 0x1d, 0x94, 0x85, 0xa4, 0x9b, 0xe8, 0x58, 0x4d, 0xc7,
	0xa6, 0xaa, 0x2d, 0x50, 0x02, 0x1a, 0x0d, 0x22, 0x69, 0x4c, 0x7a, 0xae, 0x4f, 0x79, 0x47, 0x4f,
	0x87, 0xd3, 0xe6, 0x7b, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x66, 0xe3, 0x30, 0x40, 0xf2, 0x00,
	0x00, 0x00,
}

func (m *Aggregator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Aggregator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Aggregator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintAggregator(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintAggregator(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintAggregator(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAggregator(dAtA []byte, offset int, v uint64) int {
	offset -= sovAggregator(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Aggregator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovAggregator(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAggregator(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovAggregator(uint64(l))
	}
	return n
}

func sovAggregator(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAggregator(x uint64) (n int) {
	return sovAggregator(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Aggregator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAggregator
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Aggregator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Aggregator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAggregator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAggregator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAggregator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAggregator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAggregator
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAggregator
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAggregator
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAggregator(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAggregator
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAggregator(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAggregator
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAggregator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAggregator
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAggregator
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAggregator
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAggregator
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAggregator        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAggregator          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAggregator = fmt.Errorf("proto: unexpected end of group")
)
