// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/kpi_measure.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KpiMeasure struct {
	Index     string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Kpi       string `protobuf:"bytes,2,opt,name=kpi,proto3" json:"kpi,omitempty"`
	Player    string `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	Timestamp int32  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value     string `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Mu        string `protobuf:"bytes,6,opt,name=mu,proto3" json:"mu,omitempty"`
	Creator   string `protobuf:"bytes,7,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *KpiMeasure) Reset()         { *m = KpiMeasure{} }
func (m *KpiMeasure) String() string { return proto.CompactTextString(m) }
func (*KpiMeasure) ProtoMessage()    {}
func (*KpiMeasure) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab77aa42dc85f149, []int{0}
}
func (m *KpiMeasure) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KpiMeasure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KpiMeasure.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KpiMeasure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KpiMeasure.Merge(m, src)
}
func (m *KpiMeasure) XXX_Size() int {
	return m.Size()
}
func (m *KpiMeasure) XXX_DiscardUnknown() {
	xxx_messageInfo_KpiMeasure.DiscardUnknown(m)
}

var xxx_messageInfo_KpiMeasure proto.InternalMessageInfo

func (m *KpiMeasure) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *KpiMeasure) GetKpi() string {
	if m != nil {
		return m.Kpi
	}
	return ""
}

func (m *KpiMeasure) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func (m *KpiMeasure) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *KpiMeasure) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KpiMeasure) GetMu() string {
	if m != nil {
		return m.Mu
	}
	return ""
}

func (m *KpiMeasure) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*KpiMeasure)(nil), "supsidacdisaac.pm.pm.KpiMeasure")
}

func init() { proto.RegisterFile("pm/kpi_measure.proto", fileDescriptor_ab77aa42dc85f149) }

var fileDescriptor_ab77aa42dc85f149 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xb3, 0xa9, 0x49, 0xe9, 0x1e, 0x44, 0x96, 0x20, 0x7b, 0x90, 0xa5, 0x78, 0xea, 0x25,
	0xc9, 0x41, 0x7c, 0x01, 0xaf, 0x22, 0x42, 0x8f, 0x5e, 0x64, 0xbb, 0x59, 0x74, 0x69, 0xc7, 0x1d,
	0xf6, 0x8f, 0xb4, 0x6f, 0xe1, 0x73, 0xf8, 0x24, 0x1e, 0x7b, 0xf4, 0x28, 0xc9, 0x8b, 0x48, 0x36,
	0x4a, 0x2f, 0xc3, 0xfc, 0x7e, 0x0c, 0x1f, 0x7c, 0x43, 0x2b, 0x84, 0x76, 0x8b, 0xe6, 0x19, 0xb4,
	0xf4, 0xd1, 0xe9, 0x06, 0x9d, 0x0d, 0x96, 0x55, 0x3e, 0xa2, 0x37, 0x9d, 0x54, 0x9d, 0xf1, 0x52,
	0xaa, 0x06, 0xa1, 0x41, 0xb8, 0xfe, 0x24, 0x94, 0xde, 0xa3, 0x79, 0x98, 0x4e, 0x59, 0x45, 0x0b,
	0xf3, 0xd6, 0xe9, 0x3d, 0x27, 0x4b, 0xb2, 0x5a, 0xac, 0x27, 0x60, 0x17, 0x74, 0xb6, 0x45, 0xc3,
	0xf3, 0xe4, 0xc6, 0x95, 0x5d, 0xd2, 0x12, 0x77, 0xf2, 0xa0, 0x1d, 0x9f, 0x25, 0xf9, 0x47, 0xec,
	0x8a, 0x2e, 0x82, 0x01, 0xed, 0x83, 0x04, 0xe4, 0x67, 0x4b, 0xb2, 0x2a, 0xd6, 0x27, 0x31, 0xa6,
	0xbf, 0xcb, 0x5d, 0xd4, 0xbc, 0x98, 0xd2, 0x13, 0xb0, 0x73, 0x9a, 0x43, 0xe4, 0x65, 0x52, 0x39,
	0x44, 0xc6, 0xe9, 0x5c, 0x39, 0x2d, 0x83, 0x75, 0x7c, 0x9e, 0xe4, 0x3f, 0xde, 0x3d, 0x7e, 0xf5,
	0x82, 0x1c, 0x7b, 0x41, 0x7e, 0x7a, 0x41, 0x3e, 0x06, 0x91, 0x1d, 0x07, 0x91, 0x7d, 0x0f, 0x22,
	0x7b, 0xba, 0x7d, 0x31, 0xe1, 0x35, 0x6e, 0x1a, 0x65, 0xa1, 0x4d, 0x3d, 0xeb, 0xb1, 0x68, 0x9d,
	0x9a, 0xb6, 0xca, 0x7a, 0xb0, 0xbe, 0x96, 0x88, 0xbe, 0x45, 0x68, 0xf7, 0xe3, 0x08, 0x07, 0xd4,
	0x7e, 0x53, 0xa6, 0xd7, 0xdc, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x74, 0x2e, 0x9a, 0x32,
	0x01, 0x00, 0x00,
}

func (m *KpiMeasure) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KpiMeasure) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KpiMeasure) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Mu) > 0 {
		i -= len(m.Mu)
		copy(dAtA[i:], m.Mu)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Mu)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Timestamp != 0 {
		i = encodeVarintKpiMeasure(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Player) > 0 {
		i -= len(m.Player)
		copy(dAtA[i:], m.Player)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Player)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Kpi) > 0 {
		i -= len(m.Kpi)
		copy(dAtA[i:], m.Kpi)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Kpi)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintKpiMeasure(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKpiMeasure(dAtA []byte, offset int, v uint64) int {
	offset -= sovKpiMeasure(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KpiMeasure) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	l = len(m.Kpi)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	l = len(m.Player)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovKpiMeasure(uint64(m.Timestamp))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	l = len(m.Mu)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovKpiMeasure(uint64(l))
	}
	return n
}

func sovKpiMeasure(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKpiMeasure(x uint64) (n int) {
	return sovKpiMeasure(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KpiMeasure) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKpiMeasure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KpiMeasure: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KpiMeasure: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kpi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kpi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mu", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mu = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKpiMeasure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKpiMeasure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKpiMeasure(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKpiMeasure
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKpiMeasure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKpiMeasure
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKpiMeasure
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKpiMeasure
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKpiMeasure        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKpiMeasure          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKpiMeasure = fmt.Errorf("proto: unexpected end of group")
)
