// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/lem.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Lem struct {
	Index   string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Start   int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End     int32    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Params  []string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	Players []string `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Creator string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Lem) Reset()         { *m = Lem{} }
func (m *Lem) String() string { return proto.CompactTextString(m) }
func (*Lem) ProtoMessage()    {}
func (*Lem) Descriptor() ([]byte, []int) {
	return fileDescriptor_67d2466d5bbf196f, []int{0}
}
func (m *Lem) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lem.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lem.Merge(m, src)
}
func (m *Lem) XXX_Size() int {
	return m.Size()
}
func (m *Lem) XXX_DiscardUnknown() {
	xxx_messageInfo_Lem.DiscardUnknown(m)
}

var xxx_messageInfo_Lem proto.InternalMessageInfo

func (m *Lem) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Lem) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Lem) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *Lem) GetParams() []string {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Lem) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *Lem) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Lem)(nil), "supsidacdisaac.pm.pm.Lem")
}

func init() { proto.RegisterFile("pm/lem.proto", fileDescriptor_67d2466d5bbf196f) }

var fileDescriptor_67d2466d5bbf196f = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0x86, 0xad, 0xba, 0x76, 0x89, 0xe8, 0x50, 0x44, 0x28, 0x9a, 0x84, 0xe9, 0xe4, 0xc5, 0xd6,
	0x50, 0xfa, 0x02, 0x9d, 0x0b, 0x05, 0x8f, 0xdd, 0x14, 0x59, 0xb4, 0x86, 0x5c, 0x74, 0xe8, 0x14,
	0x48, 0x9e, 0xa2, 0x7d, 0xac, 0x8e, 0x19, 0x3b, 0x16, 0xfb, 0x45, 0x8a, 0x94, 0x66, 0x39, 0xee,
	0xfb, 0xff, 0xe1, 0xe7, 0xe3, 0xb7, 0x08, 0x7a, 0xeb, 0xa0, 0xc7, 0xe0, 0xa3, 0x17, 0x6b, 0xda,
	0x23, 0x4d, 0xa3, 0xb1, 0xe3, 0x44, 0xc6, 0xd8, 0x1e, 0xa1, 0x47, 0x78, 0xf8, 0x64, 0xbc, 0x7c,
	0x71, 0x20, 0xd6, 0xbc, 0x9a, 0x76, 0xa3, 0x3b, 0x48, 0xd6, 0xb0, 0x76, 0x35, 0x9c, 0x21, 0xa5,
	0x14, 0x4d, 0x88, 0xf2, 0xaa, 0x61, 0x6d, 0x35, 0x9c, 0x41, 0xdc, 0xf1, 0xd2, 0xed, 0x46, 0x59,
	0xe6, 0x2c, 0xbd, 0xe2, 0x9e, 0xd7, 0x68, 0x82, 0x01, 0x92, 0xd7, 0x4d, 0xd9, 0xae, 0x86, 0x7f,
	0x12, 0x92, 0xdf, 0xe0, 0xd6, 0x1c, 0x5d, 0x20, 0x59, 0xe5, 0xe2, 0x82, 0xa9, 0xb1, 0xc1, 0x99,
	0xe8, 0x83, 0xac, 0xf3, 0xe2, 0x05, 0x9f, 0x5f, 0xbf, 0x67, 0xc5, 0x4e, 0xb3, 0x62, 0xbf, 0xb3,
	0x62, 0x5f, 0x8b, 0x2a, 0x4e, 0x8b, 0x2a, 0x7e, 0x16, 0x55, 0xbc, 0x3d, 0xbd, 0x4f, 0xf1, 0x63,
	0xbf, 0xe9, 0xad, 0x07, 0x9d, 0x65, 0xba, 0x64, 0xd3, 0x65, 0x1d, 0x6d, 0x3d, 0x81, 0xa7, 0xce,
	0x20, 0x92, 0x46, 0xd0, 0x87, 0x74, 0xe2, 0x11, 0x1d, 0x6d, 0xea, 0xec, 0xff, 0xf8, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x86, 0x58, 0x71, 0x45, 0x0f, 0x01, 0x00, 0x00,
}

func (m *Lem) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lem) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lem) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintLem(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Players) > 0 {
		for iNdEx := len(m.Players) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Players[iNdEx])
			copy(dAtA[i:], m.Players[iNdEx])
			i = encodeVarintLem(dAtA, i, uint64(len(m.Players[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Params) > 0 {
		for iNdEx := len(m.Params) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Params[iNdEx])
			copy(dAtA[i:], m.Params[iNdEx])
			i = encodeVarintLem(dAtA, i, uint64(len(m.Params[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.End != 0 {
		i = encodeVarintLem(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintLem(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintLem(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLem(dAtA []byte, offset int, v uint64) int {
	offset -= sovLem(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Lem) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovLem(uint64(l))
	}
	if m.Start != 0 {
		n += 1 + sovLem(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovLem(uint64(m.End))
	}
	if len(m.Params) > 0 {
		for _, s := range m.Params {
			l = len(s)
			n += 1 + l + sovLem(uint64(l))
		}
	}
	if len(m.Players) > 0 {
		for _, s := range m.Players {
			l = len(s)
			n += 1 + l + sovLem(uint64(l))
		}
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovLem(uint64(l))
	}
	return n
}

func sovLem(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLem(x uint64) (n int) {
	return sovLem(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Lem) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLem
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lem: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lem: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLem
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLem
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLem
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLem
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Params = append(m.Params, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Players", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLem
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLem
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Players = append(m.Players, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLem
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLem
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLem
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLem(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLem
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLem(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLem
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLem
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLem
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLem
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLem
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLem
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLem        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLem          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLem = fmt.Errorf("proto: unexpected end of group")
)
