// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pm/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetDsoRequest struct {
}

func (m *QueryGetDsoRequest) Reset()         { *m = QueryGetDsoRequest{} }
func (m *QueryGetDsoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDsoRequest) ProtoMessage()    {}
func (*QueryGetDsoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{0}
}
func (m *QueryGetDsoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDsoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDsoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDsoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDsoRequest.Merge(m, src)
}
func (m *QueryGetDsoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDsoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDsoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDsoRequest proto.InternalMessageInfo

type QueryGetDsoResponse struct {
	Dso Dso `protobuf:"bytes,1,opt,name=Dso,proto3" json:"Dso"`
}

func (m *QueryGetDsoResponse) Reset()         { *m = QueryGetDsoResponse{} }
func (m *QueryGetDsoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDsoResponse) ProtoMessage()    {}
func (*QueryGetDsoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{1}
}
func (m *QueryGetDsoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDsoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDsoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDsoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDsoResponse.Merge(m, src)
}
func (m *QueryGetDsoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDsoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDsoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDsoResponse proto.InternalMessageInfo

func (m *QueryGetDsoResponse) GetDso() Dso {
	if m != nil {
		return m.Dso
	}
	return Dso{}
}

type QueryGetPlayerRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetPlayerRequest) Reset()         { *m = QueryGetPlayerRequest{} }
func (m *QueryGetPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPlayerRequest) ProtoMessage()    {}
func (*QueryGetPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{2}
}
func (m *QueryGetPlayerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPlayerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPlayerRequest.Merge(m, src)
}
func (m *QueryGetPlayerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPlayerRequest proto.InternalMessageInfo

func (m *QueryGetPlayerRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetPlayerResponse struct {
	Player Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player"`
}

func (m *QueryGetPlayerResponse) Reset()         { *m = QueryGetPlayerResponse{} }
func (m *QueryGetPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPlayerResponse) ProtoMessage()    {}
func (*QueryGetPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{3}
}
func (m *QueryGetPlayerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPlayerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPlayerResponse.Merge(m, src)
}
func (m *QueryGetPlayerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPlayerResponse proto.InternalMessageInfo

func (m *QueryGetPlayerResponse) GetPlayer() Player {
	if m != nil {
		return m.Player
	}
	return Player{}
}

type QueryAllPlayerRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPlayerRequest) Reset()         { *m = QueryAllPlayerRequest{} }
func (m *QueryAllPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPlayerRequest) ProtoMessage()    {}
func (*QueryAllPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{4}
}
func (m *QueryAllPlayerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPlayerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPlayerRequest.Merge(m, src)
}
func (m *QueryAllPlayerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPlayerRequest proto.InternalMessageInfo

func (m *QueryAllPlayerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPlayerResponse struct {
	Player     []Player            `protobuf:"bytes,1,rep,name=player,proto3" json:"player"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPlayerResponse) Reset()         { *m = QueryAllPlayerResponse{} }
func (m *QueryAllPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPlayerResponse) ProtoMessage()    {}
func (*QueryAllPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{5}
}
func (m *QueryAllPlayerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPlayerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPlayerResponse.Merge(m, src)
}
func (m *QueryAllPlayerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPlayerResponse proto.InternalMessageInfo

func (m *QueryAllPlayerResponse) GetPlayer() []Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *QueryAllPlayerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAggregatorRequest struct {
}

func (m *QueryGetAggregatorRequest) Reset()         { *m = QueryGetAggregatorRequest{} }
func (m *QueryGetAggregatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregatorRequest) ProtoMessage()    {}
func (*QueryGetAggregatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{6}
}
func (m *QueryGetAggregatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregatorRequest.Merge(m, src)
}
func (m *QueryGetAggregatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregatorRequest proto.InternalMessageInfo

type QueryGetAggregatorResponse struct {
	Aggregator Aggregator `protobuf:"bytes,1,opt,name=Aggregator,proto3" json:"Aggregator"`
}

func (m *QueryGetAggregatorResponse) Reset()         { *m = QueryGetAggregatorResponse{} }
func (m *QueryGetAggregatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAggregatorResponse) ProtoMessage()    {}
func (*QueryGetAggregatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{7}
}
func (m *QueryGetAggregatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAggregatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAggregatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAggregatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAggregatorResponse.Merge(m, src)
}
func (m *QueryGetAggregatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAggregatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAggregatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAggregatorResponse proto.InternalMessageInfo

func (m *QueryGetAggregatorResponse) GetAggregator() Aggregator {
	if m != nil {
		return m.Aggregator
	}
	return Aggregator{}
}

type QueryGetLemRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetLemRequest) Reset()         { *m = QueryGetLemRequest{} }
func (m *QueryGetLemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLemRequest) ProtoMessage()    {}
func (*QueryGetLemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{8}
}
func (m *QueryGetLemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLemRequest.Merge(m, src)
}
func (m *QueryGetLemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLemRequest proto.InternalMessageInfo

func (m *QueryGetLemRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

type QueryGetLemResponse struct {
	Lem Lem `protobuf:"bytes,1,opt,name=lem,proto3" json:"lem"`
}

func (m *QueryGetLemResponse) Reset()         { *m = QueryGetLemResponse{} }
func (m *QueryGetLemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLemResponse) ProtoMessage()    {}
func (*QueryGetLemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{9}
}
func (m *QueryGetLemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLemResponse.Merge(m, src)
}
func (m *QueryGetLemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLemResponse proto.InternalMessageInfo

func (m *QueryGetLemResponse) GetLem() Lem {
	if m != nil {
		return m.Lem
	}
	return Lem{}
}

type QueryAllLemRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLemRequest) Reset()         { *m = QueryAllLemRequest{} }
func (m *QueryAllLemRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLemRequest) ProtoMessage()    {}
func (*QueryAllLemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{10}
}
func (m *QueryAllLemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLemRequest.Merge(m, src)
}
func (m *QueryAllLemRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLemRequest proto.InternalMessageInfo

func (m *QueryAllLemRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLemResponse struct {
	Lem        []Lem               `protobuf:"bytes,1,rep,name=lem,proto3" json:"lem"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLemResponse) Reset()         { *m = QueryAllLemResponse{} }
func (m *QueryAllLemResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLemResponse) ProtoMessage()    {}
func (*QueryAllLemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf833bf452d8635e, []int{11}
}
func (m *QueryAllLemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLemResponse.Merge(m, src)
}
func (m *QueryAllLemResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLemResponse proto.InternalMessageInfo

func (m *QueryAllLemResponse) GetLem() []Lem {
	if m != nil {
		return m.Lem
	}
	return nil
}

func (m *QueryAllLemResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetDsoRequest)(nil), "supsidacdisaac.pm.pm.QueryGetDsoRequest")
	proto.RegisterType((*QueryGetDsoResponse)(nil), "supsidacdisaac.pm.pm.QueryGetDsoResponse")
	proto.RegisterType((*QueryGetPlayerRequest)(nil), "supsidacdisaac.pm.pm.QueryGetPlayerRequest")
	proto.RegisterType((*QueryGetPlayerResponse)(nil), "supsidacdisaac.pm.pm.QueryGetPlayerResponse")
	proto.RegisterType((*QueryAllPlayerRequest)(nil), "supsidacdisaac.pm.pm.QueryAllPlayerRequest")
	proto.RegisterType((*QueryAllPlayerResponse)(nil), "supsidacdisaac.pm.pm.QueryAllPlayerResponse")
	proto.RegisterType((*QueryGetAggregatorRequest)(nil), "supsidacdisaac.pm.pm.QueryGetAggregatorRequest")
	proto.RegisterType((*QueryGetAggregatorResponse)(nil), "supsidacdisaac.pm.pm.QueryGetAggregatorResponse")
	proto.RegisterType((*QueryGetLemRequest)(nil), "supsidacdisaac.pm.pm.QueryGetLemRequest")
	proto.RegisterType((*QueryGetLemResponse)(nil), "supsidacdisaac.pm.pm.QueryGetLemResponse")
	proto.RegisterType((*QueryAllLemRequest)(nil), "supsidacdisaac.pm.pm.QueryAllLemRequest")
	proto.RegisterType((*QueryAllLemResponse)(nil), "supsidacdisaac.pm.pm.QueryAllLemResponse")
}

func init() { proto.RegisterFile("pm/query.proto", fileDescriptor_cf833bf452d8635e) }

var fileDescriptor_cf833bf452d8635e = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4f, 0x6b, 0x13, 0x4d,
	0x1c, 0xc7, 0x33, 0xcd, 0xd3, 0x40, 0xe7, 0x11, 0x85, 0x69, 0x14, 0x9b, 0xd6, 0xb5, 0x4c, 0xb5,
	0xc6, 0xd6, 0xec, 0xd8, 0x8a, 0x17, 0x6f, 0x29, 0xa5, 0xf5, 0x10, 0xb0, 0x06, 0x4f, 0x22, 0xc8,
	0x24, 0x19, 0xd6, 0x85, 0x99, 0xcc, 0x34, 0xb3, 0x91, 0x16, 0x11, 0xa1, 0x17, 0x6f, 0xa2, 0xf4,
	0x28, 0xbe, 0x9f, 0x1e, 0x0b, 0x5e, 0x3c, 0x88, 0x48, 0xeb, 0x0b, 0x91, 0x9d, 0x99, 0x74, 0x37,
	0xcd, 0x76, 0x13, 0xa1, 0x97, 0xb0, 0x3b, 0xf9, 0xfd, 0xf9, 0xcc, 0xfc, 0xbe, 0xdf, 0x59, 0x78,
	0x55, 0x09, 0xb2, 0xdb, 0x67, 0xbd, 0x7d, 0x5f, 0xf5, 0x64, 0x24, 0x51, 0x59, 0xf7, 0x95, 0x0e,
	0x3b, 0xb4, 0xdd, 0x09, 0x35, 0xa5, 0x6d, 0x5f, 0x09, 0x5f, 0x89, 0xca, 0x42, 0x20, 0x65, 0xc0,
	0x19, 0xa1, 0x2a, 0x24, 0xb4, 0xdb, 0x95, 0x11, 0x8d, 0x42, 0xd9, 0xd5, 0x36, 0xa7, 0xb2, 0xd2,
	0x96, 0x5a, 0x48, 0x4d, 0x5a, 0x54, 0x33, 0x5b, 0x8c, 0xbc, 0x5d, 0x6b, 0xb1, 0x88, 0xae, 0x11,
	0x45, 0x83, 0xb0, 0x6b, 0x82, 0x5d, 0xec, 0x15, 0x25, 0x48, 0x47, 0x4b, 0xf7, 0x76, 0x4d, 0x09,
	0xa2, 0x38, 0xdd, 0x67, 0x3d, 0xb7, 0x30, 0xab, 0x04, 0xa1, 0x41, 0xd0, 0x63, 0x01, 0x8d, 0x64,
	0x2f, 0x95, 0xc3, 0x99, 0x70, 0x6f, 0xe5, 0x40, 0x06, 0xd2, 0x3c, 0x92, 0xf8, 0xc9, 0xae, 0xe2,
	0x32, 0x44, 0xcf, 0xe3, 0xce, 0xdb, 0x2c, 0xda, 0xd4, 0xb2, 0xc9, 0x76, 0xfb, 0x4c, 0x47, 0xf8,
	0x29, 0x9c, 0x1d, 0x5a, 0xd5, 0x4a, 0x76, 0x35, 0x43, 0x6b, 0xb0, 0xb8, 0xa9, 0xe5, 0x4d, 0xb0,
	0x08, 0xaa, 0xff, 0xaf, 0xcf, 0xf9, 0x59, 0x5b, 0xf6, 0x37, 0xb5, 0xdc, 0xf8, 0xef, 0xe8, 0xd7,
	0xed, 0x42, 0x33, 0x8e, 0xc5, 0x35, 0x78, 0x7d, 0x50, 0x69, 0xc7, 0x00, 0xbb, 0x16, 0xa8, 0x0c,
	0xa7, 0xc3, 0x6e, 0x87, 0xed, 0x99, 0x6a, 0x33, 0x4d, 0xfb, 0x82, 0x5f, 0xc0, 0x1b, 0xe7, 0xc3,
	0x5d, 0xef, 0x27, 0xb0, 0x64, 0x77, 0xec, 0xda, 0x2f, 0x64, 0xb7, 0xb7, 0x59, 0x8e, 0xc0, 0x65,
	0xe0, 0xd7, 0x0e, 0xa2, 0xce, 0xf9, 0x30, 0xc4, 0x16, 0x84, 0xc9, 0x49, 0xbb, 0xc2, 0xcb, 0xbe,
	0x1d, 0x8b, 0x1f, 0x8f, 0xc5, 0xb7, 0x33, 0x76, 0x63, 0xf1, 0x77, 0x68, 0xc0, 0x5c, 0x6e, 0x33,
	0x95, 0x89, 0xbf, 0x01, 0xc7, 0x9d, 0xea, 0x90, 0xc1, 0x5d, 0xfc, 0x37, 0x6e, 0xb4, 0x3d, 0x84,
	0x37, 0x65, 0xf0, 0xee, 0x8d, 0xc5, 0xb3, 0x8d, 0x87, 0xf8, 0xe6, 0xe1, 0xdc, 0xe0, 0x58, 0xeb,
	0x67, 0x2a, 0x19, 0x0c, 0xbb, 0x03, 0x2b, 0x59, 0x7f, 0x3a, 0xfe, 0x2d, 0x08, 0x93, 0x55, 0x77,
	0x44, 0x8b, 0xd9, 0x7b, 0x48, 0xe2, 0xdc, 0x3e, 0x52, 0x99, 0x78, 0x25, 0x11, 0x5a, 0x83, 0x89,
	0x7c, 0x15, 0xa4, 0xe4, 0x67, 0x62, 0x13, 0xf9, 0x71, 0x26, 0xf2, 0xe5, 0xd7, 0x60, 0x62, 0x20,
	0x3f, 0xce, 0x04, 0x7e, 0xe5, 0xba, 0xd6, 0x39, 0x4f, 0x75, 0xbd, 0xac, 0xb1, 0x7f, 0x01, 0x0e,
	0x74, 0x50, 0xfe, 0x3c, 0x68, 0x71, 0x52, 0xd0, 0x4b, 0x1b, 0xf5, 0xfa, 0xcf, 0x12, 0x9c, 0x36,
	0x4c, 0xe8, 0x83, 0x71, 0x2b, 0xaa, 0x66, 0xf7, 0x1f, 0x75, 0x7d, 0xe5, 0xfe, 0x04, 0x91, 0xb6,
	0x23, 0x5e, 0x3a, 0xf8, 0xfe, 0xe7, 0x70, 0xea, 0x16, 0x9a, 0x27, 0x26, 0xa5, 0x16, 0xe7, 0xd4,
	0x4c, 0x12, 0x89, 0xaf, 0x26, 0x73, 0x57, 0xa1, 0x43, 0x00, 0x4b, 0x56, 0xd7, 0x68, 0x35, 0xbf,
	0xf4, 0x90, 0x2b, 0x2b, 0x0f, 0x26, 0x0b, 0x76, 0x28, 0xbe, 0x41, 0xa9, 0xa2, 0xe5, 0x8b, 0x50,
	0xac, 0x99, 0xc8, 0x3b, 0xa3, 0xad, 0xf7, 0xe8, 0x13, 0x80, 0x33, 0xb6, 0x44, 0x9d, 0xf3, 0x5c,
	0xb0, 0xf3, 0xd7, 0x45, 0x2e, 0xd8, 0x88, 0xf3, 0xf1, 0xb2, 0x01, 0x5b, 0x44, 0x5e, 0x3e, 0x18,
	0xfa, 0x0a, 0xd2, 0x16, 0x43, 0x24, 0x7f, 0xf7, 0x23, 0xfe, 0xad, 0x3c, 0x9c, 0x3c, 0xc1, 0x91,
	0xad, 0x18, 0xb2, 0x3b, 0x08, 0x5f, 0x44, 0x96, 0x7c, 0x4a, 0xd0, 0x47, 0x00, 0x8b, 0x0d, 0x26,
	0xc6, 0xc9, 0x28, 0x71, 0xd7, 0x38, 0x19, 0xa5, 0x8c, 0x82, 0x57, 0x0d, 0xc8, 0x5d, 0xb4, 0x74,
	0x11, 0x08, 0x67, 0xe2, 0x6c, 0x70, 0x07, 0x00, 0x96, 0x1a, 0x4c, 0xc4, 0x53, 0xab, 0xe6, 0x0f,
	0x62, 0x42, 0x98, 0x61, 0xd7, 0x8e, 0xd7, 0x34, 0x67, 0x62, 0xe3, 0xd9, 0xd1, 0x89, 0x07, 0x8e,
	0x4f, 0x3c, 0xf0, 0xfb, 0xc4, 0x03, 0x9f, 0x4f, 0xbd, 0xc2, 0xf1, 0xa9, 0x57, 0xf8, 0x71, 0xea,
	0x15, 0x5e, 0x3e, 0x0e, 0xc2, 0xe8, 0x4d, 0xbf, 0xe5, 0xb7, 0xa5, 0x18, 0x2d, 0x60, 0x8d, 0x5c,
	0xa3, 0x4a, 0xe9, 0xb8, 0xd2, 0x5e, 0xfc, 0x13, 0xed, 0x2b, 0xa6, 0x5b, 0x25, 0xf3, 0x1d, 0x7e,
	0xf4, 0x37, 0x00, 0x00, 0xff, 0xff, 0x90, 0x00, 0xb8, 0xa1, 0x51, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a dso by index.
	Dso(ctx context.Context, in *QueryGetDsoRequest, opts ...grpc.CallOption) (*QueryGetDsoResponse, error)
	// Queries a player by index.
	Player(ctx context.Context, in *QueryGetPlayerRequest, opts ...grpc.CallOption) (*QueryGetPlayerResponse, error)
	// Queries a list of player items.
	PlayerAll(ctx context.Context, in *QueryAllPlayerRequest, opts ...grpc.CallOption) (*QueryAllPlayerResponse, error)
	// Queries a aggregator by index.
	Aggregator(ctx context.Context, in *QueryGetAggregatorRequest, opts ...grpc.CallOption) (*QueryGetAggregatorResponse, error)
	// Queries a lem by index.
	Lem(ctx context.Context, in *QueryGetLemRequest, opts ...grpc.CallOption) (*QueryGetLemResponse, error)
	// Queries a list of lem items.
	LemAll(ctx context.Context, in *QueryAllLemRequest, opts ...grpc.CallOption) (*QueryAllLemResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Dso(ctx context.Context, in *QueryGetDsoRequest, opts ...grpc.CallOption) (*QueryGetDsoResponse, error) {
	out := new(QueryGetDsoResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/Dso", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Player(ctx context.Context, in *QueryGetPlayerRequest, opts ...grpc.CallOption) (*QueryGetPlayerResponse, error) {
	out := new(QueryGetPlayerResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/Player", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PlayerAll(ctx context.Context, in *QueryAllPlayerRequest, opts ...grpc.CallOption) (*QueryAllPlayerResponse, error) {
	out := new(QueryAllPlayerResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/PlayerAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Aggregator(ctx context.Context, in *QueryGetAggregatorRequest, opts ...grpc.CallOption) (*QueryGetAggregatorResponse, error) {
	out := new(QueryGetAggregatorResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/Aggregator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lem(ctx context.Context, in *QueryGetLemRequest, opts ...grpc.CallOption) (*QueryGetLemResponse, error) {
	out := new(QueryGetLemResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/Lem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LemAll(ctx context.Context, in *QueryAllLemRequest, opts ...grpc.CallOption) (*QueryAllLemResponse, error) {
	out := new(QueryAllLemResponse)
	err := c.cc.Invoke(ctx, "/supsidacdisaac.pm.pm.Query/LemAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a dso by index.
	Dso(context.Context, *QueryGetDsoRequest) (*QueryGetDsoResponse, error)
	// Queries a player by index.
	Player(context.Context, *QueryGetPlayerRequest) (*QueryGetPlayerResponse, error)
	// Queries a list of player items.
	PlayerAll(context.Context, *QueryAllPlayerRequest) (*QueryAllPlayerResponse, error)
	// Queries a aggregator by index.
	Aggregator(context.Context, *QueryGetAggregatorRequest) (*QueryGetAggregatorResponse, error)
	// Queries a lem by index.
	Lem(context.Context, *QueryGetLemRequest) (*QueryGetLemResponse, error)
	// Queries a list of lem items.
	LemAll(context.Context, *QueryAllLemRequest) (*QueryAllLemResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Dso(ctx context.Context, req *QueryGetDsoRequest) (*QueryGetDsoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dso not implemented")
}
func (*UnimplementedQueryServer) Player(ctx context.Context, req *QueryGetPlayerRequest) (*QueryGetPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Player not implemented")
}
func (*UnimplementedQueryServer) PlayerAll(ctx context.Context, req *QueryAllPlayerRequest) (*QueryAllPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayerAll not implemented")
}
func (*UnimplementedQueryServer) Aggregator(ctx context.Context, req *QueryGetAggregatorRequest) (*QueryGetAggregatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Aggregator not implemented")
}
func (*UnimplementedQueryServer) Lem(ctx context.Context, req *QueryGetLemRequest) (*QueryGetLemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lem not implemented")
}
func (*UnimplementedQueryServer) LemAll(ctx context.Context, req *QueryAllLemRequest) (*QueryAllLemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LemAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Dso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDsoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Dso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/Dso",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Dso(ctx, req.(*QueryGetDsoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Player_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Player(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/Player",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Player(ctx, req.(*QueryGetPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PlayerAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PlayerAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/PlayerAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PlayerAll(ctx, req.(*QueryAllPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Aggregator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAggregatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Aggregator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/Aggregator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Aggregator(ctx, req.(*QueryGetAggregatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/Lem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lem(ctx, req.(*QueryGetLemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LemAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LemAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supsidacdisaac.pm.pm.Query/LemAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LemAll(ctx, req.(*QueryAllLemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supsidacdisaac.pm.pm.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Dso",
			Handler:    _Query_Dso_Handler,
		},
		{
			MethodName: "Player",
			Handler:    _Query_Player_Handler,
		},
		{
			MethodName: "PlayerAll",
			Handler:    _Query_PlayerAll_Handler,
		},
		{
			MethodName: "Aggregator",
			Handler:    _Query_Aggregator_Handler,
		},
		{
			MethodName: "Lem",
			Handler:    _Query_Lem_Handler,
		},
		{
			MethodName: "LemAll",
			Handler:    _Query_LemAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pm/query.proto",
}

func (m *QueryGetDsoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDsoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDsoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetDsoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDsoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDsoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Dso.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetPlayerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPlayerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPlayerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPlayerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPlayerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPlayerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Player.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPlayerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPlayerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPlayerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPlayerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPlayerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPlayerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Player) > 0 {
		for iNdEx := len(m.Player) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Player[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetAggregatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAggregatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAggregatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Aggregator.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Lem.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Lem) > 0 {
		for iNdEx := len(m.Lem) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lem[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetDsoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetDsoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Dso.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetPlayerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPlayerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Player.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPlayerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPlayerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Player) > 0 {
		for _, e := range m.Player {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAggregatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetAggregatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Aggregator.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetLemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Lem.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Lem) > 0 {
		for _, e := range m.Lem {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetDsoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDsoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDsoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDsoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDsoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDsoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dso", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Dso.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPlayerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPlayerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPlayerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPlayerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPlayerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPlayerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Player.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPlayerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPlayerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPlayerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPlayerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPlayerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPlayerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Player", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Player = append(m.Player, Player{})
			if err := m.Player[len(m.Player)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAggregatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAggregatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAggregatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aggregator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Aggregator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Lem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lem = append(m.Lem, Lem{})
			if err := m.Lem[len(m.Lem)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
