// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tsdb/measure.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Measure struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeseriesID string `protobuf:"bytes,2,opt,name=timeseriesID,proto3" json:"timeseriesID,omitempty"`
	Ts           string `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Value        string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Creator      string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *Measure) Reset()         { *m = Measure{} }
func (m *Measure) String() string { return proto.CompactTextString(m) }
func (*Measure) ProtoMessage()    {}
func (*Measure) Descriptor() ([]byte, []int) {
	return fileDescriptor_58240db372ba76f7, []int{0}
}
func (m *Measure) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Measure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Measure.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Measure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Measure.Merge(m, src)
}
func (m *Measure) XXX_Size() int {
	return m.Size()
}
func (m *Measure) XXX_DiscardUnknown() {
	xxx_messageInfo_Measure.DiscardUnknown(m)
}

var xxx_messageInfo_Measure proto.InternalMessageInfo

func (m *Measure) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Measure) GetTimeseriesID() string {
	if m != nil {
		return m.TimeseriesID
	}
	return ""
}

func (m *Measure) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func (m *Measure) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Measure) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*Measure)(nil), "supsidacdisaac.tsdb.tsdb.Measure")
}

func init() { proto.RegisterFile("tsdb/measure.proto", fileDescriptor_58240db372ba76f7) }

var fileDescriptor_58240db372ba76f7 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe3, 0xd0, 0x52, 0x61, 0x21, 0x06, 0xab, 0x83, 0xc5, 0x60, 0x55, 0x9d, 0xba, 0x24,
	0x1e, 0x98, 0x58, 0x11, 0x0b, 0x03, 0x4b, 0xd9, 0xd8, 0x1c, 0xdb, 0x0a, 0x96, 0x88, 0x6c, 0xf9,
	0x2e, 0x08, 0x06, 0xde, 0x81, 0xc7, 0x62, 0xcc, 0xc8, 0x88, 0x92, 0x17, 0x41, 0xb9, 0x88, 0xa1,
	0x8b, 0x7d, 0xff, 0x7f, 0xff, 0x9d, 0xf4, 0x1d, 0x17, 0x08, 0xae, 0xd1, 0x9d, 0x37, 0xd0, 0x67,
	0x5f, 0xa7, 0x1c, 0x31, 0x0a, 0x09, 0x7d, 0x82, 0xe0, 0x8c, 0x75, 0x01, 0x8c, 0xb1, 0xf5, 0x1c,
	0xa1, 0xe7, 0x7a, 0xdb, 0xc6, 0x36, 0x52, 0x48, 0xcf, 0xd5, 0x92, 0xdf, 0x7f, 0xf2, 0xcd, 0xe3,
	0xb2, 0x40, 0x5c, 0xf1, 0x32, 0x38, 0xc9, 0x76, 0xec, 0xb0, 0x3a, 0x96, 0xc1, 0x89, 0x3d, 0xbf,
	0xc4, 0xd0, 0x79, 0xf0, 0x39, 0x78, 0x78, 0xb8, 0x97, 0xe5, 0x8e, 0x1d, 0x2e, 0x8e, 0x27, 0xde,
	0x3c, 0x83, 0x20, 0xcf, 0xa8, 0x53, 0x22, 0x88, 0x2d, 0x5f, 0xbf, 0x99, 0xd7, 0xde, 0xcb, 0x15,
	0x59, 0x8b, 0x10, 0x92, 0x6f, 0x6c, 0xf6, 0x06, 0x63, 0x96, 0x6b, 0xf2, 0xff, 0xe5, 0xdd, 0xd3,
	0xf7, 0xa8, 0xd8, 0x30, 0x2a, 0xf6, 0x3b, 0x2a, 0xf6, 0x35, 0xa9, 0x62, 0x98, 0x54, 0xf1, 0x33,
	0xa9, 0xe2, 0xf9, 0xb6, 0x0d, 0xf8, 0xd2, 0x37, 0xb5, 0x8d, 0x9d, 0x26, 0xa6, 0x6a, 0x86, 0xaa,
	0x88, 0x4a, 0xdb, 0x08, 0x5d, 0x84, 0xca, 0xa4, 0x04, 0x9a, 0x8e, 0xf0, 0xbe, 0x7c, 0xf8, 0x91,
	0x3c, 0x34, 0xe7, 0x84, 0x76, 0xf3, 0x17, 0x00, 0x00, 0xff, 0xff, 0x09, 0x57, 0x87, 0xbc, 0x20,
	0x01, 0x00, 0x00,
}

func (m *Measure) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Measure) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Measure) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintMeasure(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintMeasure(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Ts) > 0 {
		i -= len(m.Ts)
		copy(dAtA[i:], m.Ts)
		i = encodeVarintMeasure(dAtA, i, uint64(len(m.Ts)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TimeseriesID) > 0 {
		i -= len(m.TimeseriesID)
		copy(dAtA[i:], m.TimeseriesID)
		i = encodeVarintMeasure(dAtA, i, uint64(len(m.TimeseriesID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintMeasure(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMeasure(dAtA []byte, offset int, v uint64) int {
	offset -= sovMeasure(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Measure) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovMeasure(uint64(m.Id))
	}
	l = len(m.TimeseriesID)
	if l > 0 {
		n += 1 + l + sovMeasure(uint64(l))
	}
	l = len(m.Ts)
	if l > 0 {
		n += 1 + l + sovMeasure(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovMeasure(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovMeasure(uint64(l))
	}
	return n
}

func sovMeasure(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMeasure(x uint64) (n int) {
	return sovMeasure(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Measure) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeasure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Measure: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Measure: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeseriesID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeseriesID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ts = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeasure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMeasure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMeasure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMeasure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMeasure(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMeasure
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeasure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMeasure
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMeasure
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMeasure
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMeasure        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMeasure          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMeasure = fmt.Errorf("proto: unexpected end of group")
)
